# INTEX EDA + ML Pipeline

This notebook:
- Loads and profiles all CSVs in this folder
- Builds a resident-level modeling table by aggregating related tables
- Trains a reproducible scikit-learn pipeline to predict a target (default: `current_risk_level`)

> Tip: If you want a different target, change `TARGET_COL` below (e.g., `case_status`, `reintegration_status`).

In [1]:
from __future__ import annotations

import os
from pathlib import Path

import numpy as np
import pandas as pd

pd.set_option("display.max_columns", 200)
pd.set_option("display.width", 140)

DATA_DIR = Path.cwd()  # assumes you opened this notebook from the same folder as the CSVs
DATA_DIR

PosixPath('/Users/masonzarges/Desktop/INTEX Data')

In [2]:
# Load all CSVs in the folder into a dict of DataFrames
csv_paths = sorted(DATA_DIR.glob("*.csv"))
if not csv_paths:
    raise FileNotFoundError(f"No CSV files found in {DATA_DIR}")

dfs: dict[str, pd.DataFrame] = {}
for p in csv_paths:
    key = p.stem
    dfs[key] = pd.read_csv(p)

list(dfs.keys()), {k: v.shape for k, v in dfs.items()}

(['home_visitations',
  'in_kind_donation_items',
  'incident_reports',
  'intervention_plans',
  'partner_assignments',
  'partners',
  'process_recordings',
  'public_impact_snapshots',
  'residents',
  'safehouse_monthly_metrics',
  'safehouses',
  'social_media_posts',
  'supporters'],
 {'home_visitations': (1337, 14),
  'in_kind_donation_items': (129, 9),
  'incident_reports': (100, 12),
  'intervention_plans': (180, 11),
  'partner_assignments': (48, 9),
  'partners': (30, 12),
  'process_recordings': (2819, 15),
  'public_impact_snapshots': (50, 7),
  'residents': (60, 49),
  'safehouse_monthly_metrics': (450, 11),
  'safehouses': (9, 13),
  'social_media_posts': (812, 39),
  'supporters': (60, 15)})

In [3]:
def profile_df(df: pd.DataFrame, name: str, n: int = 5) -> None:
    display(pd.DataFrame({
        "dtype": df.dtypes.astype(str),
        "missing": df.isna().sum(),
        "missing_%": (df.isna().mean() * 100).round(2),
        "n_unique": df.nunique(dropna=True),
    }).sort_values(["missing", "n_unique"], ascending=[False, False]).head(30))
    print(f"\n{name}: shape={df.shape}")
    display(df.head(n))

for name, df in dfs.items():
    print("=" * 90)
    profile_df(df, name)

==========================================================================================

                           dtype  missing  missing_%  n_unique
follow_up_notes           object      549      41.06         1
family_members_present    object      425      31.79       100
visitation_id              int64        0       0.00      1337
visit_date                object        0       0.00       783
resident_id                int64        0       0.00        58
social_worker             object        0       0.00        20
location_visited          object        0       0.00         6
visit_type                object        0       0.00         5
purpose                   object        0       0.00         5
observations              object        0       0.00         5
family_cooperation_level  object        0       0.00         4
visit_outcome             object        0       0.00         4
safety_concerns_noted       bool        0       0.00         2
follow_up_needed            bool        0       0.00         2

home_visitations: shape=(1337, 14)

,visitation_id,resident_id,visit_date,social_worker,visit_type,location_visited,family_members_present,purpose,observations,family_cooperation_level,safety_concerns_noted,follow_up_needed,follow_up_notes,visit_outcome
0,1,1,2023-11-02,SW-04,Routine Follow-Up,Proposed Foster Home,Lopez (Parent); Diaz (Sibling),Visitation for routine follow-up,Visit observations recorded during routine fol...,Neutral,True,False,Follow-up scheduled,Favorable
1,2,1,2023-11-22,SW-12,Routine Follow-Up,Church,Mendoza (Parent); Mendoza (Sibling),Visitation for routine follow-up,Visit observations recorded during routine fol...,Neutral,False,False,NaN,Favorable
2,3,1,2023-12-14,SW-16,Post-Placement Monitoring,Barangay Office,Santos (Parent); Torres (Sibling),Visitation for post-placement monitoring,Visit observations recorded during post-placem...,Uncooperative,False,True,Follow-up scheduled,Unfavorable
3,4,1,2023-12-18,SW-07,Reintegration Assessment,Proposed Foster Home,Cruz (Parent); Mendoza (Sibling),Visitation for reintegration assessment,Visit observations recorded during reintegrati...,Cooperative,False,True,Follow-up scheduled,Needs Improvement
4,5,1,2023-12-24,SW-05,Post-Placement Monitoring,Community Center,NaN,Visitation for post-placement monitoring,Visit observations recorded during post-placem...,Cooperative,False,True,NaN,Unfavorable

==========================================================================================

                        dtype  missing  missing_%  n_unique
item_id                 int64        0        0.0       129
estimated_unit_value  float64        0        0.0       129
donation_id             int64        0        0.0        98
quantity                int64        0        0.0        28
item_name              object        0        0.0         9
item_category          object        0        0.0         7
unit_of_measure        object        0        0.0         5
intended_use           object        0        0.0         5
received_condition     object        0        0.0         3

in_kind_donation_items: shape=(129, 9)

   item_id  donation_id        item_name    item_category  quantity unit_of_measure  estimated_unit_value intended_use received_condition
0        1            5  School Supplies  SchoolMaterials        10            sets                779.49       Health                New
1        2            9             Bags             Food        16           packs                793.39      Shelter               Good
2        3           13        Medicines         Supplies        12            sets                774.73       Health               Good
3        4           15        Furniture          Medical        28           packs                318.23      Hygiene                New
4        5           27        Medicines          Hygiene        15           boxes                385.34    Education                New

==========================================================================================

                     dtype  missing  missing_%  n_unique
resolution_date     object       29       29.0        70
incident_id          int64        0        0.0       100
description         object        0        0.0       100
incident_date       object        0        0.0        97
resident_id          int64        0        0.0        44
reported_by         object        0        0.0        20
safehouse_id         int64        0        0.0         9
incident_type       object        0        0.0         7
response_taken      object        0        0.0         7
severity            object        0        0.0         3
resolved              bool        0        0.0         2
follow_up_required    bool        0        0.0         2

incident_reports: shape=(100, 12)

,incident_id,resident_id,safehouse_id,incident_date,incident_type,severity,description,response_taken,resolved,resolution_date,reported_by,follow_up_required
0,1,1,4,2024-06-22,Medical,Medium,Medical incident reported on 2024-06-22,Response to medical,True,2024-07-01,SW-19,False
1,2,1,4,2026-02-10,Security,High,Security incident reported on 2026-02-10,Response to security,False,NaN,SW-20,True
2,3,1,4,2024-02-03,RunawayAttempt,Low,RunawayAttempt incident reported on 2024-02-03,Response to runawayattempt,True,2024-02-10,SW-18,False
3,4,1,4,2025-04-17,Behavioral,Low,Behavioral incident reported on 2025-04-17,Response to behavioral,True,2025-04-23,SW-12,False
4,5,3,1,2025-05-12,SelfHarm,High,SelfHarm incident reported on 2025-05-12,Response to selfharm,False,NaN,SW-08,True

==========================================================================================

                        dtype  missing  missing_%  n_unique
case_conference_date   object       48      26.67       128
plan_id                 int64        0       0.00       180
resident_id             int64        0       0.00        60
services_provided      object        0       0.00        40
target_date            object        0       0.00        27
created_at             object        0       0.00        27
updated_at             object        0       0.00        27
status                 object        0       0.00         5
target_value          float64        0       0.00         4
plan_category          object        0       0.00         3
plan_description       object        0       0.00         3

intervention_plans: shape=(180, 11)

,plan_id,resident_id,plan_category,plan_description,services_provided,target_value,target_date,status,case_conference_date,created_at,updated_at
0,1,1,Safety,Maintain a stable and safe environment,"Healing, Legal Services, Teaching",4.20,2024-02-01,On Hold,2023-11-01,2023-10-01 00:00:00,2024-03-01 00:00:00
1,2,1,Education,Improve participation and course completion,"Caring, Legal Services, Healing",0.85,2024-02-01,In Progress,2024-01-30,2023-10-01 00:00:00,2024-03-01 00:00:00
2,3,1,Physical Health,Improve nutrition and overall wellbeing,"Teaching, Healing, Caring",4.20,2024-02-01,On Hold,2023-10-24,2023-10-01 00:00:00,2024-03-01 00:00:00
3,4,2,Safety,Maintain a stable and safe environment,Legal Services,4.20,2023-11-01,On Hold,2023-11-02,2023-03-01 00:00:00,2023-12-01 00:00:00
4,5,2,Education,Improve participation and course completion,"Healing, Caring",0.85,2023-11-01,Open,2023-04-26,2023-03-01 00:00:00,2023-12-01 00:00:00

==========================================================================================

                        dtype  missing  missing_%  n_unique
assignment_end         object       43      89.58         1
safehouse_id          float64       10      20.83         9
assignment_id           int64        0       0.00        48
partner_id              int64        0       0.00        30
assignment_start       object        0       0.00        30
responsibility_notes   object        0       0.00         7
program_area           object        0       0.00         5
is_primary               bool        0       0.00         2
status                 object        0       0.00         2

partner_assignments: shape=(48, 9)

,assignment_id,partner_id,safehouse_id,program_area,assignment_start,assignment_end,responsibility_notes,is_primary,status
0,1,1,8.0,Operations,2022-01-01,NaN,SafehouseOps support for safehouse operations,True,Active
1,2,1,9.0,Operations,2022-01-01,NaN,SafehouseOps support for safehouse operations,False,Active
2,3,2,4.0,Wellbeing,2022-01-21,NaN,Evaluation support for safehouse operations,True,Active
3,4,3,9.0,Education,2022-02-10,NaN,Education support for safehouse operations,True,Active
4,5,3,6.0,Education,2022-02-10,NaN,Education support for safehouse operations,False,Active

==========================================================================================

               dtype  missing  missing_%  n_unique
end_date      object       27       90.0         1
partner_id     int64        0        0.0        30
partner_name  object        0        0.0        30
contact_name  object        0        0.0        30
email         object        0        0.0        30
phone         object        0        0.0        30
start_date    object        0        0.0        30
role_type     object        0        0.0         7
region        object        0        0.0         3
partner_type  object        0        0.0         2
status        object        0        0.0         2
notes         object        0        0.0         2

partners: shape=(30, 12)

,partner_id,partner_name,partner_type,role_type,contact_name,email,phone,region,status,start_date,end_date,notes
0,1,Ana Reyes,Organization,SafehouseOps,Ana Reyes,ana-reyes@hopepartners.ph,+63 993 532 6574,Luzon,Active,2022-01-01,NaN,Primary contractor
1,2,Maria Santos,Individual,Evaluation,Maria Santos,maria-santos@pldt.net.ph,+63 927 194 7224,Luzon,Active,2022-01-21,NaN,Primary contractor
2,3,Elena Cruz,Individual,Education,Elena Cruz,elena-cruz@eastern.com.ph,+63 966 926 1711,Mindanao,Active,2022-02-10,NaN,Primary contractor
3,4,Sofia Dizon,Organization,Logistics,Sofia Dizon,sofia-dizon@bayanihanfoundation.ph,+63 947 400 6925,Visayas,Active,2022-03-02,NaN,Primary contractor
4,5,Grace Flores,Individual,SafehouseOps,Grace Flores,grace-flores@yahoo.com.ph,+63 991 333 5741,Visayas,Active,2022-03-22,NaN,Primary contractor

==========================================================================================

                            dtype  missing  missing_%  n_unique
notes_restricted          float64     2819      100.0         0
recording_id                int64        0        0.0      2819
session_date               object        0        0.0      1017
session_narrative          object        0        0.0       137
session_duration_minutes    int64        0        0.0        91
resident_id                 int64        0        0.0        60
interventions_applied      object        0        0.0        40
social_worker              object        0        0.0        20
emotional_state_observed   object        0        0.0         8
emotional_state_end        object        0        0.0         6
follow_up_actions          object        0        0.0         5
session_type               object        0        0.0         2
progress_noted               bool        0        0.0         2
concerns_flagged             bool        0        0.0         2
referral_made                bool        0        0.0         2

process_recordings: shape=(2819, 15)

,recording_id,resident_id,session_date,social_worker,session_type,session_duration_minutes,emotional_state_observed,emotional_state_end,session_narrative,interventions_applied,follow_up_actions,progress_noted,concerns_flagged,referral_made,notes_restricted
0,1,1,2023-11-08,SW-02,Individual,62,Angry,Hopeful,Session with resident. Type: Individual. Durat...,Caring,Referral to specialist,True,True,False,NaN
1,2,1,2023-11-11,SW-10,Group,83,Distressed,Sad,Session with resident. Type: Group. Duration: ...,Legal Services,Referral to specialist,True,True,True,NaN
2,3,1,2023-11-24,SW-01,Individual,77,Anxious,Hopeful,Session with resident. Type: Individual. Durat...,"Healing, Legal Services",Referral to specialist,True,False,False,NaN
3,4,1,2023-12-01,SW-19,Group,77,Hopeful,Happy,Session with resident. Type: Group. Duration: ...,"Teaching, Legal Services",Schedule follow-up session,True,False,False,NaN
4,5,1,2023-12-06,SW-15,Individual,77,Happy,Happy,Session with resident. Type: Individual. Durat...,Teaching,Schedule follow-up session,True,False,False,NaN

==========================================================================================

                      dtype  missing  missing_%  n_unique
snapshot_id           int64        0        0.0        50
snapshot_date        object        0        0.0        50
headline             object        0        0.0        50
metric_payload_json  object        0        0.0        50
published_at         object        0        0.0        50
summary_text         object        0        0.0        39
is_published           bool        0        0.0         1

public_impact_snapshots: shape=(50, 7)

,snapshot_id,snapshot_date,headline,summary_text,metric_payload_json,is_published,published_at
0,1,2023-01-01,Lighthouse Sanctuary Impact Update - January 2023,Anonymized aggregate report: 60 residents acti...,"{'month': '2023-01', 'avg_health_score': 3.03,...",True,2023-01-01
1,2,2023-02-01,Lighthouse Sanctuary Impact Update - February ...,Anonymized aggregate report: 60 residents acti...,"{'month': '2023-02', 'avg_health_score': 3.13,...",True,2023-02-01
2,3,2023-03-01,Lighthouse Sanctuary Impact Update - March 2023,Anonymized aggregate report: 60 residents acti...,"{'month': '2023-03', 'avg_health_score': 3.16,...",True,2023-03-01
3,4,2023-04-01,Lighthouse Sanctuary Impact Update - April 2023,Anonymized aggregate report: 60 residents acti...,"{'month': '2023-04', 'avg_health_score': 3.2, ...",True,2023-04-01
4,5,2023-05-01,Lighthouse Sanctuary Impact Update - May 2023,Anonymized aggregate report: 60 residents acti...,"{'month': '2023-05', 'avg_health_score': 3.2, ...",True,2023-05-01

==========================================================================================

                            dtype  missing  missing_%  n_unique
notes_restricted          float64       60     100.00         0
pwd_type                   object       57      95.00         2
special_needs_diagnosis    object       54      90.00         3
date_closed                object       30      50.00        30
date_colb_obtained         object       24      40.00        35
referring_agency_person    object       24      40.00        27
date_colb_registered       object       13      21.67        45
date_case_study_prepared   object       11      18.33        48
reintegration_type         object        5       8.33         5
resident_id                 int64        0       0.00        60
case_control_no            object        0       0.00        60
internal_code              object        0       0.00        60
date_of_birth              object        0       0.00        57
date_of_admission          object        0       0.00        57
date_enrolled              object        0       0.00        57
created_at                 object        0       0.00        57
present_age                object        0       0.00        44
age_upon_admission         object        0       0.00        34
length_of_stay             object        0       0.00        27
assigned_social_worker     object        0       0.00        18
place_of_birth             object        0       0.00        14
safehouse_id                int64        0       0.00         9
religion                   object        0       0.00         8
referral_source            object        0       0.00         6
initial_case_assessment    object        0       0.00         5
case_category              object        0       0.00         4
reintegration_status       object        0       0.00         4
initial_risk_level         object        0       0.00         4
current_risk_level         object        0       0.00         4
case_status                object        0       0.00         3

residents: shape=(60, 49)

,resident_id,case_control_no,internal_code,safehouse_id,case_status,sex,date_of_birth,birth_status,place_of_birth,religion,case_category,sub_cat_orphaned,sub_cat_trafficked,sub_cat_child_labor,sub_cat_physical_abuse,sub_cat_sexual_abuse,sub_cat_osaec,sub_cat_cicl,sub_cat_at_risk,sub_cat_street_child,sub_cat_child_with_hiv,is_pwd,pwd_type,has_special_needs,special_needs_diagnosis,family_is_4ps,family_solo_parent,family_indigenous,family_parent_pwd,family_informal_settler,date_of_admission,age_upon_admission,present_age,length_of_stay,referral_source,referring_agency_person,date_colb_registered,date_colb_obtained,assigned_social_worker,initial_case_assessment,date_case_study_prepared,reintegration_type,reintegration_status,initial_risk_level,current_risk_level,date_enrolled,date_closed,created_at,notes_restricted
0,1,C0043,LS-0001,4,Active,F,2008-08-31,Marital,Davao City,Unspecified,Neglected,False,False,False,False,False,False,False,False,False,False,False,NaN,True,Speech Impairment,False,False,False,False,False,2023-10-17,15 Years 9 months,17 Years 6 months,2 Years 4 months,NGO,Ramon Cruz,NaN,NaN,SW-15,For Reunification,2023-12-14,Foster Care,In Progress,Critical,High,2023-10-17,NaN,2023-10-17 00:00:00,NaN
1,2,C2530,LS-0002,3,Closed,F,2008-04-23,Marital,Cebu City,Seventh-day Adventist,Surrendered,False,False,False,False,False,False,False,True,True,False,False,NaN,False,NaN,False,False,True,False,False,2023-03-18,15 Years 5 months,17 Years 10 months,1 Years 9 months,Government Agency,Ana Cruz,2023-07-06,2024-12-30,SW-14,For Continued Care,2023-04-10,Family Reunification,Completed,Medium,Medium,2023-03-18,2025-01-06,2023-03-18 00:00:00,NaN
2,3,C3946,LS-0003,1,Active,F,2007-01-31,Marital,Manila,Roman Catholic,Surrendered,False,False,False,False,True,False,False,False,False,False,False,NaN,False,NaN,False,False,False,False,False,2024-05-24,18 Years 3 months,19 Years 1 months,1 Years 9 months,Government Agency,NaN,2024-08-02,2024-09-21,SW-20,For Independent Living,NaN,Foster Care,Completed,Medium,Medium,2024-05-24,NaN,2024-05-24 00:00:00,NaN
3,4,C3116,LS-0004,2,Active,F,2012-06-29,Marital,Davao City,Evangelical,Neglected,False,False,False,False,False,False,True,False,False,False,False,NaN,False,NaN,False,False,False,False,False,2024-09-27,12 Years 11 months,13 Years 8 months,1 Years 5 months,Court Order,NaN,NaN,NaN,SW-15,For Reunification,2024-10-25,NaN,On Hold,High,Low,2024-09-27,NaN,2024-09-27 00:00:00,NaN
4,5,C9132,LS-0005,4,Transferred,F,2009-04-20,Marital,Pasay City,Buddhism,Surrendered,False,False,False,True,False,True,False,False,False,False,True,Intellectual,False,NaN,True,False,False,False,False,2024-01-10,15 Years 4 months,16 Years 10 months,0 Years 9 months,Self-Referral,Mark Dizon,2024-02-18,NaN,SW-04,For Independent Living,2024-02-14,Family Reunification,Completed,Medium,Low,2024-01-10,2024-10-08,2024-01-10 00:00:00,NaN

==========================================================================================

                           dtype  missing  missing_%  n_unique
notes                    float64      450     100.00         0
avg_education_progress   float64      197      43.78       198
avg_health_score         float64      197      43.78        83
metric_id                  int64        0       0.00       450
month_start               object        0       0.00        50
month_end                 object        0       0.00        50
process_recording_count    int64        0       0.00        25
home_visitation_count      int64        0       0.00        14
safehouse_id               int64        0       0.00         9
active_residents           int64        0       0.00         6
incident_count             int64        0       0.00         4

safehouse_monthly_metrics: shape=(450, 11)

,metric_id,safehouse_id,month_start,month_end,active_residents,avg_education_progress,avg_health_score,process_recording_count,home_visitation_count,incident_count,notes
0,1,1,2023-01-01,2023-01-31,10,NaN,NaN,0,0,0,NaN
1,2,1,2023-02-01,2023-02-28,10,NaN,NaN,0,0,0,NaN
2,3,1,2023-03-01,2023-03-31,10,56.30,3.03,1,0,0,NaN
3,4,1,2023-04-01,2023-04-30,10,51.90,3.07,5,4,1,NaN
4,5,1,2023-05-01,2023-05-31,10,51.25,3.17,0,2,0,NaN

==========================================================================================

                     dtype  missing  missing_%  n_unique
notes              float64        9      100.0         0
safehouse_id         int64        0        0.0         9
safehouse_code      object        0        0.0         9
name                object        0        0.0         9
city                object        0        0.0         9
province            object        0        0.0         9
open_date           object        0        0.0         9
capacity_girls       int64        0        0.0         6
current_occupancy    int64        0        0.0         5
capacity_staff       int64        0        0.0         4
region              object        0        0.0         3
country             object        0        0.0         1
status              object        0        0.0         1

safehouses: shape=(9, 13)

,safehouse_id,safehouse_code,name,region,city,province,country,open_date,status,capacity_girls,capacity_staff,current_occupancy,notes
0,1,SH01,Lighthouse Safehouse 1,Luzon,Quezon City,Metro Manila,Philippines,2022-01-01,Active,8,4,8,NaN
1,2,SH02,Lighthouse Safehouse 2,Visayas,Cebu City,Cebu,Philippines,2022-02-15,Active,10,5,8,NaN
2,3,SH03,Lighthouse Safehouse 3,Mindanao,Davao City,Davao del Sur,Philippines,2022-04-01,Active,9,4,9,NaN
3,4,SH04,Lighthouse Safehouse 4,Visayas,Iloilo City,Iloilo,Philippines,2022-05-16,Active,12,4,12,NaN
4,5,SH05,Lighthouse Safehouse 5,Luzon,Baguio City,Benguet,Philippines,2022-06-30,Active,11,4,9,NaN

==========================================================================================

                                dtype  missing  missing_%  n_unique
watch_time_seconds            float64      741      91.26        71
subscriber_count_at_post      float64      741      91.26        67
avg_view_duration_seconds     float64      741      91.26        64
forwards                      float64      719      88.55        66
boost_budget_php              float64      685      84.36       127
campaign_name                  object      580      71.43         4
video_views                   float64      479      58.99       328
call_to_action_type            object      319      39.29         4
hashtags                       object      148      18.23       404
post_id                         int64        0       0.00       812
platform_post_id               object        0       0.00       812
post_url                       object        0       0.00       812
created_at                     object        0       0.00       812
impressions                     int64        0       0.00       790
reach                           int64        0       0.00       754
caption                        object        0       0.00       728
engagement_rate               float64        0       0.00       675
estimated_donation_value_php  float64        0       0.00       523
likes                           int64        0       0.00       452
profile_visits                  int64        0       0.00       302
click_throughs                  int64        0       0.00       284
shares                          int64        0       0.00       256
comments                        int64        0       0.00       249
saves                           int64        0       0.00       153
caption_length                  int64        0       0.00       124
donation_referrals              int64        0       0.00        95
follower_count_at_post          int64        0       0.00        41
post_hour                       int64        0       0.00        24
content_topic                  object        0       0.00         9
platform                       object        0       0.00         7

social_media_posts: shape=(812, 39)

,post_id,platform,platform_post_id,post_url,created_at,day_of_week,post_hour,post_type,media_type,caption,hashtags,num_hashtags,mentions_count,has_call_to_action,call_to_action_type,content_topic,sentiment_tone,caption_length,features_resident_story,campaign_name,is_boosted,boost_budget_php,impressions,reach,likes,comments,shares,saves,click_throughs,video_views,engagement_rate,profile_visits,donation_referrals,estimated_donation_value_php,follower_count_at_post,watch_time_seconds,avg_view_duration_seconds,subscriber_count_at_post,forwards
0,318,WhatsApp,wa_4293211912553134,https://whatsapp.com/channel/lighthouse_ph/429...,2023-01-05 18:52:00,Thursday,18,FundraisingAppeal,Text,"This is hard to ask, but our reserve is gone. ...",NaN,0,3,True,LearnMore,Education,Grateful,157,False,NaN,False,NaN,1580,1093,118,36,22,9,48,NaN,0.1105,21,10,21473.25,1522,NaN,NaN,NaN,50.0
1,529,Instagram,ig_5129900136072862,https://instagram.com/p/sYhZp-0AvhH,2023-01-06 11:30:00,Friday,11,EducationalContent,Photo,What does freedom mean to a trafficking surviv...,"#SurvivorStrong, #BeTheChange, #HumanTrafficki...",4,0,False,NaN,Education,Celebratory,150,False,NaN,False,NaN,6362,4395,548,110,149,59,85,NaN,0.1745,335,2,4708.45,1833,NaN,NaN,NaN,NaN
2,86,LinkedIn,li_2326736034499294,https://linkedin.com/feed/update/urn:li:activi...,2023-01-08 10:14:00,Sunday,10,EventPromotion,Text,SAVE THE DATE! Join us on January 21 for Fundr...,NaN,0,0,False,NaN,Reintegration,Urgent,138,False,NaN,False,NaN,554,336,27,7,12,4,3,NaN,0.1411,8,0,0.00,457,NaN,NaN,NaN,NaN
3,380,Instagram,ig_4154485528046983,https://instagram.com/p/1LSXA225Jpv,2023-01-09 15:06:00,Monday,15,ThankYou,Video,Every donation is a prayer answered. Thank you...,"#ProtectChildren, #BeTheChange",2,1,False,NaN,Education,Emotional,113,False,NaN,False,NaN,4309,2948,190,55,45,16,35,3313.0,0.0677,62,0,0.00,1796,NaN,NaN,NaN,NaN
4,425,TikTok,tk_7166643297225195,https://tiktok.com/@lighthouse_ph/video/817153...,2023-01-09 15:59:00,Monday,15,ThankYou,Reel,Big thanks to Juan for the recent donation. Yo...,"#SurvivorStrong, #EndViolence, #HumanTrafficki...",4,1,True,LearnMore,Education,Hopeful,129,False,NaN,True,4030.64,23175,14008,728,232,141,79,474,17974.0,0.0802,172,2,8351.49,916,NaN,NaN,NaN,NaN

==========================================================================================

                      dtype  missing  missing_%  n_unique
organization_name    object       56      93.33         4
first_name           object        4       6.67        56
last_name            object        4       6.67        55
first_donation_date  object        1       1.67        58
supporter_id          int64        0       0.00        60
display_name         object        0       0.00        60
email                object        0       0.00        60
phone                object        0       0.00        60
created_at           object        0       0.00        60
supporter_type       object        0       0.00         6
acquisition_channel  object        0       0.00         6
country              object        0       0.00         4
relationship_type    object        0       0.00         3
region               object        0       0.00         3
status               object        0       0.00         2

supporters: shape=(60, 15)

,supporter_id,supporter_type,display_name,organization_name,first_name,last_name,relationship_type,region,country,email,phone,status,created_at,first_donation_date,acquisition_channel
0,1,SocialMediaAdvocate,Mila Alvarez,NaN,Mila,Alvarez,Local,Luzon,Philippines,mila-alvarez@smart.com.ph,+63 997 578 1887,Active,2022-01-01 00:00:00,2023-07-02,SocialMedia
1,2,Volunteer,Aria Brown,NaN,Aria,Brown,Local,Mindanao,Philippines,aria-brown@pldt.net.ph,+63 927 354 4139,Active,2022-01-06 00:00:00,2023-09-25,SocialMedia
2,3,MonetaryDonor,Noah Chen,NaN,Noah,Chen,Local,Luzon,Philippines,noah-chen@globe.com.ph,+63 917 553 2604,Active,2022-01-11 00:00:00,2023-06-25,SocialMedia
3,4,MonetaryDonor,Liam Diaz,NaN,Liam,Diaz,PartnerOrganization,Mindanao,Philippines,liam-diaz@globe.com.ph,+63 945 516 8956,Active,2022-01-16 00:00:00,2026-03-01,Church
4,5,InKindDonor,Emma Evans,NaN,Emma,Evans,PartnerOrganization,Mindanao,Philippines,emma-evans@yahoo.com.ph,+63 995 371 8454,Active,2022-01-21 00:00:00,2024-01-18,Website

## Build a resident-level modeling dataset

We’ll use `residents` as the main table and left-join/aggregate related tables by `resident_id`.

Default prediction target: `residents.current_risk_level` (multiclass classification).

In [4]:
TARGET_COL = "current_risk_level"  # change if desired
ID_COL = "resident_id"

residents = dfs["residents"].copy()

# Basic cleanup: normalize obvious boolean-like columns to actual bool where possible
bool_like_cols = [c for c in residents.columns if c.startswith("sub_cat_") or c.startswith("family_") or c in {"is_pwd", "has_special_needs"}]
for c in bool_like_cols:
    if c in residents.columns:
        residents[c] = residents[c].map({True: True, False: False, "True": True, "False": False}).astype("boolean")

# Parse key dates (errors coerced to NaT)
for c in [
    "date_of_birth",
    "date_of_admission",
    "date_enrolled",
    "date_closed",
    "created_at",
]:
    if c in residents.columns:
        residents[c] = pd.to_datetime(residents[c], errors="coerce")

residents[[ID_COL, TARGET_COL]].head()

   resident_id current_risk_level
0            1               High
1            2             Medium
2            3             Medium
3            4                Low
4            5                Low

In [5]:
def agg_incidents(inc: pd.DataFrame) -> pd.DataFrame:
    inc = inc.copy()
    if "incident_date" in inc.columns:
        inc["incident_date"] = pd.to_datetime(inc["incident_date"], errors="coerce")

    out = inc.groupby(ID_COL).agg(
        incident_count=("incident_id", "count"),
        incident_high_sev=("severity", lambda s: (s.astype(str).str.lower() == "high").sum()),
        incident_unresolved=("resolved", lambda s: (~s.fillna(False).astype(bool)).sum()),
        incident_types_n=("incident_type", pd.Series.nunique),
        last_incident_date=("incident_date", "max"),
    )
    out["days_since_last_incident"] = (
        (pd.Timestamp.today().normalize() - out["last_incident_date"]).dt.days
    )
    return out.drop(columns=["last_incident_date"])


def agg_visits(vis: pd.DataFrame) -> pd.DataFrame:
    vis = vis.copy()
    if "visit_date" in vis.columns:
        vis["visit_date"] = pd.to_datetime(vis["visit_date"], errors="coerce")

    out = vis.groupby(ID_COL).agg(
        home_visit_count=("visitation_id", "count"),
        home_visit_types_n=("visit_type", pd.Series.nunique),
        home_visit_outcomes_n=("visit_outcome", pd.Series.nunique),
        safety_concerns_count=("safety_concerns_noted", lambda s: s.fillna(False).astype(bool).sum()),
        follow_up_needed_count=("follow_up_needed", lambda s: s.fillna(False).astype(bool).sum()),
        last_visit_date=("visit_date", "max"),
    )
    out["days_since_last_visit"] = (
        (pd.Timestamp.today().normalize() - out["last_visit_date"]).dt.days
    )
    return out.drop(columns=["last_visit_date"])


def agg_plans(plans: pd.DataFrame) -> pd.DataFrame:
    plans = plans.copy()
    for c in ["target_date", "case_conference_date", "created_at", "updated_at"]:
        if c in plans.columns:
            plans[c] = pd.to_datetime(plans[c], errors="coerce")

    out = plans.groupby(ID_COL).agg(
        intervention_plan_count=("plan_id", "count"),
        intervention_categories_n=("plan_category", pd.Series.nunique),
        intervention_status_n=("status", pd.Series.nunique),
        intervention_target_value_mean=("target_value", "mean"),
        last_plan_update=("updated_at", "max"),
    )
    out["days_since_last_plan_update"] = (
        (pd.Timestamp.today().normalize() - out["last_plan_update"]).dt.days
    )
    return out.drop(columns=["last_plan_update"])


def agg_sessions(proc: pd.DataFrame) -> pd.DataFrame:
    proc = proc.copy()
    if "session_date" in proc.columns:
        proc["session_date"] = pd.to_datetime(proc["session_date"], errors="coerce")

    out = proc.groupby(ID_COL).agg(
        session_count=("recording_id", "count"),
        session_minutes_sum=("session_duration_minutes", "sum"),
        session_types_n=("session_type", pd.Series.nunique),
        concerns_flagged_count=("concerns_flagged", lambda s: s.fillna(False).astype(bool).sum()),
        referral_made_count=("referral_made", lambda s: s.fillna(False).astype(bool).sum()),
        last_session_date=("session_date", "max"),
    )
    out["days_since_last_session"] = (
        (pd.Timestamp.today().normalize() - out["last_session_date"]).dt.days
    )
    return out.drop(columns=["last_session_date"])


features = residents.copy()

if "incident_reports" in dfs:
    features = features.merge(agg_incidents(dfs["incident_reports"]), how="left", left_on=ID_COL, right_index=True)
if "home_visitations" in dfs:
    features = features.merge(agg_visits(dfs["home_visitations"]), how="left", left_on=ID_COL, right_index=True)
if "intervention_plans" in dfs:
    features = features.merge(agg_plans(dfs["intervention_plans"]), how="left", left_on=ID_COL, right_index=True)
if "process_recordings" in dfs:
    features = features.merge(agg_sessions(dfs["process_recordings"]), how="left", left_on=ID_COL, right_index=True)

features.shape, features.columns[:15]

((60, 71),
 Index(['resident_id', 'case_control_no', 'internal_code', 'safehouse_id', 'case_status', 'sex', 'date_of_birth', 'birth_status',
        'place_of_birth', 'religion', 'case_category', 'sub_cat_orphaned', 'sub_cat_trafficked', 'sub_cat_child_labor',
        'sub_cat_physical_abuse'],
       dtype='object'))

In [6]:
# Prepare train table

df_model = features.copy()

# Drop columns that are identifiers or free-text notes (usually not stable / can leak)
drop_cols = [
    "case_control_no",
    "internal_code",
    "referring_agency_person",
    "notes_restricted",
]
df_model = df_model.drop(columns=[c for c in drop_cols if c in df_model.columns])

# Target + filters
if TARGET_COL not in df_model.columns:
    raise KeyError(f"TARGET_COL={TARGET_COL!r} not found in residents columns")

# Keep rows with a known target
mask = df_model[TARGET_COL].notna() & (df_model[TARGET_COL].astype(str).str.len() > 0)
df_train = df_model.loc[mask].copy()

# Basic feature engineering from dates
if "date_of_birth" in df_train.columns:
    df_train["age_years"] = ((pd.Timestamp.today().normalize() - df_train["date_of_birth"]).dt.days / 365.25).round(2)

if "date_of_admission" in df_train.columns:
    df_train["days_since_admission"] = (pd.Timestamp.today().normalize() - df_train["date_of_admission"]).dt.days

# Drop raw datetime columns (keep engineered numeric features instead)
datetime_cols = df_train.select_dtypes(include=["datetime64[ns]", "datetime64[ns, UTC]"]).columns.tolist()
df_train = df_train.drop(columns=datetime_cols)

# Separate X/y
y = df_train[TARGET_COL].astype(str)
X = df_train.drop(columns=[TARGET_COL])

X.shape, y.value_counts(dropna=False).head(20)

((60, 63),
 current_risk_level
 Low         34
 Medium      20
 High         5
 Critical     1
 Name: count, dtype: int64)

In [7]:
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.metrics import classification_report
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder
from sklearn.linear_model import LogisticRegression

# Identify column types
numeric_cols = X.select_dtypes(include=["number"]).columns.tolist()
cat_cols = [c for c in X.columns if c not in numeric_cols]

# Ensure categorical columns are plain python objects (avoids edge-cases with pandas string dtypes)
X = X.copy()
for c in cat_cols:
    X[c] = X[c].astype("object")

# Preprocessing
numeric_tf = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="median")),
])

categorical_tf = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("onehot", OneHotEncoder(handle_unknown="ignore")),
])

preprocess = ColumnTransformer(
    transformers=[
        ("num", numeric_tf, numeric_cols),
        ("cat", categorical_tf, cat_cols),
    ],
    remainder="drop",
)

# Model
clf = LogisticRegression(max_iter=3000)

pipe = Pipeline(steps=[
    ("preprocess", preprocess),
    ("model", clf),
])

# Robust split: only stratify when every class has >= 2 rows
class_counts = y.value_counts()
use_stratify = class_counts.min() >= 2
stratify_arg = y if use_stratify else None
if not use_stratify:
    print(
        "Warning: some classes have <2 rows; disabling stratified split.\n"
        f"Class counts: {class_counts.to_dict()}"
    )

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=stratify_arg,
)

pipe.fit(X_train, y_train)

y_pred = pipe.predict(X_test)
print(classification_report(y_test, y_pred, zero_division=0))

Warning: some classes have <2 rows; disabling stratified split.
Class counts: {'Low': 34, 'Medium': 20, 'High': 5, 'Critical': 1}
              precision    recall  f1-score   support

    Critical       0.00      0.00      0.00         0
        High       0.00      0.00      0.00         1
         Low       0.80      0.50      0.62         8
      Medium       0.33      0.67      0.44         3

    accuracy                           0.50        12
   macro avg       0.28      0.29      0.26        12
weighted avg       0.62      0.50      0.52        12

/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 3000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=3000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [8]:
# Train on all labeled rows and generate predictions for all residents
pipe.fit(X, y)

# Build prediction frame for all residents (including those with missing target)
df_pred = df_model.copy()

# Recreate the same engineered date features used for training
if "date_of_birth" in df_pred.columns:
    dob = pd.to_datetime(df_pred["date_of_birth"], errors="coerce")
    df_pred["age_years"] = ((pd.Timestamp.today().normalize() - dob).dt.days / 365.25).round(2)

if "date_of_admission" in df_pred.columns:
    doa = pd.to_datetime(df_pred["date_of_admission"], errors="coerce")
    df_pred["days_since_admission"] = (pd.Timestamp.today().normalize() - doa).dt.days

# Drop datetime columns (pipeline expects same column types as training)
datetime_cols = df_pred.select_dtypes(include=["datetime64[ns]", "datetime64[ns, UTC]"]).columns.tolist()
df_pred = df_pred.drop(columns=datetime_cols)

X_all = df_pred.drop(columns=[TARGET_COL]) if TARGET_COL in df_pred.columns else df_pred

pred_label = pipe.predict(X_all)

pred_out = pd.DataFrame({
    ID_COL: df_pred[ID_COL],
    f"pred_{TARGET_COL}": pred_label,
})

# Optional: add probabilities (for multiclass, one column per class)
if hasattr(pipe.named_steps["model"], "predict_proba"):
    proba = pipe.predict_proba(X_all)
    classes = pipe.named_steps["model"].classes_
    for i, cls in enumerate(classes):
        pred_out[f"proba_{cls}"] = proba[:, i]

pred_out.head()

/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 3000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=3000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

   resident_id pred_current_risk_level  proba_Critical    proba_High     proba_Low  proba_Medium
0            1                    High    5.347441e-17  9.999695e-01  1.122748e-07      0.000030
1            2                  Medium   1.532674e-106  7.478916e-10  2.792344e-02      0.972077
2            3                  Medium    8.872400e-83  2.969671e-05  1.402563e-01      0.859714
3            4                     Low    7.663693e-12  3.245910e-02  8.934149e-01      0.074126
4            5                     Low   1.960180e-100  1.831850e-03  9.291689e-01      0.068999

In [9]:
# Save predictions
out_path = DATA_DIR / f"predictions_{TARGET_COL}.csv"
pred_out.to_csv(out_path, index=False)
out_path

PosixPath('/Users/masonzarges/Desktop/INTEX Data/predictions_current_risk_level.csv')